name: Rust

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions/setup-rust@v1

    - name: Build for Windows
      run: cargo build --release --target=x86_64-pc-windows-msvc
